# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20180224_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='lead_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hub.User'),
        ),
    ]
