# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_auto_20180303_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
