# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=45)),
                ('sex', models.CharField(default='', max_length=4)),
                ('nation', models.CharField(default='', max_length=45)),
                ('phone', models.CharField(default='', max_length=11)),
                ('email', models.CharField(default='', max_length=45)),
                ('qq', models.CharField(default='', max_length=13)),
                ('hobby', models.CharField(default='', max_length=45)),
                ('address', models.CharField(default='', max_length=45)),
                ('organization', models.CharField(default='', max_length=45)),
                ('tech', models.CharField(default='', max_length=45)),
                ('apartment', models.CharField(default='', max_length=20)),
                ('agree_to_allocation', models.IntegerField(default=0)),
                ('await', models.TextField(default='')),
                ('plan', models.TextField(default='')),
                ('assess', models.TextField(default='')),
            ],
        ),
    ]
