# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-14 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registertable',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='registertable',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
